[package]
name = "core"
version = "0.1.0"
authors = ["Stephen A <stephen@creativelogic.me>"]
license = "MIT"
edition = "2018"
exclude = ["artifacts.json"]

[dependencies]
reducer = "2.1"
serde = { version = "1.0.111", features = ["derive"] }
